server:
  port: 8080

spring:
  application:
    name: board-service
  datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/final_test?serverTimezone=Asia/Seoul
#     username: root
#     password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k6e102.p.ssafy.io:3307/modong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: plainYorgurt%
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true



eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: https://k6e102.p.ssafy.io:8761/eureka
    register-with-eureka: true
    fetch-registry: true
