server:
  port: 0
#  port: ${random.int(50000,50001)}
#  address: 127.0.0.1
  redis:
    host: localhost
    port: 6379
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true
  #  sleuth:
  #    sampler:
  #      probability: 1.0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/msa_db?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: admin
  #    url: jdbc:mysql://j6e206.p.ssafy.io:3306/jpmp?serverTimezone=UTC&characterEncoding=UTF-8
  #    driver-class-name : com.mysql.cj.jdbc.Driver
  #    hikari:
  #      username: SSAFY
  #      password: SSAFY

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  devtools:
    livereload:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #    prefer-ip-address: true
  #    ip-address: ${server.address}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

greeting:
  message: Welcome to the Simple E-commerce.

logging:
  level:
    com.example.userservice.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus

#token:
#  expiration_time: 86400000
#  secret: usertoken123123123asdasdasdasdasdfasdf123123123jsdlfkjasdlfkjasdlfkasjdlfkjasldkfasdgsdfgdfgqweqweqweqweqwe