
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:



        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method= POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/busrefresh
            - Method= POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method= GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/register
            - Method= POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method= POST , DELETE , PUT
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/v3/**
            - Method=GET, POST, DELETE, PUT
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**
            - Method=GET, POST, DELETE, PUT
          filters:
            - RemoveRequestHeader=Cookie
#            - AuthorizationHeaderFilter
            #post는 인증없이되어야하지만 다른경우 인증요구

        # [chat] swagger
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/v3/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chat-service/(?<segment>.*), /$\{segment}

        # [chat] REST API
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/chat/**
            - Method=GET, POST, DELETE, PUT
          filters:
            - RemoveRequestHeader=Cookie

        # [chat] STOMP
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chat-service/message/**
            - Method=GET, POST, DELETE, PUT
          filters:
            - RemoveRequestHeader=Cookie

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus