
server:
  port: 11334

spring:
  application:
    name: order-service

  redis:
    host: k6e102.p.ssafy.io
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/modong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://k6e102.p.ssafy.io:3307/modong?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: plainYorgurt%
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    devtools:
      livereload:
        enabled: true



eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #    prefer-ip-address: true
  #    ip-address: ${server.address}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
